# Generated by Django 5.0.6 on 2024-07-05 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0002_customuser_is_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='brand_name',
            field=models.CharField(max_length=150, verbose_name='브랜드명(작가명)'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='company_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='회사명'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='contact_number',
            field=models.CharField(max_length=15, verbose_name='연락처'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_artist',
            field=models.BooleanField(default=False, verbose_name='작가 여부'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='position',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='직책'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_id',
            field=models.CharField(max_length=150, unique=True, verbose_name='아이디'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=150, verbose_name='이름'),
        ),
    ]
