# Generated by Django 5.0.6 on 2024-07-15 08:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(max_length=150, verbose_name='작가명')),
                ('artwork_image', models.ImageField(upload_to='artworks/', verbose_name='작품 이미지')),
                ('artwork_title', models.CharField(max_length=150, verbose_name='작품명')),
                ('artwork_description', models.TextField(verbose_name='작품 설명')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
