# Generated by Django 5.0.6 on 2024-08-15 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='artist_name',
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(default='Name', max_length=100)),
                ('intro', models.CharField(blank=True, default='Appealing Description', max_length=200, null=True)),
                ('career', models.TextField(blank=True, default='Career', max_length=200, null=True)),
                ('photo1', models.ImageField(blank=True, null=True, upload_to='portfolio_images/')),
                ('description1', models.CharField(blank=True, default='Project Name', max_length=100, null=True)),
                ('photo2', models.ImageField(blank=True, null=True, upload_to='portfolio_images/')),
                ('description2', models.CharField(blank=True, default='Project Name', max_length=100, null=True)),
                ('photo3', models.ImageField(blank=True, null=True, upload_to='portfolio_images/')),
                ('description3', models.CharField(blank=True, default='Project Name', max_length=100, null=True)),
                ('photo4', models.ImageField(blank=True, null=True, upload_to='portfolio_images/')),
                ('description4', models.CharField(blank=True, default='Project Name', max_length=100, null=True)),
                ('photo5', models.ImageField(blank=True, null=True, upload_to='portfolio_images/')),
                ('description5', models.CharField(blank=True, default='Project Name', max_length=100, null=True)),
                ('photo6', models.ImageField(blank=True, null=True, upload_to='portfolio_images/')),
                ('description6', models.CharField(blank=True, default='Project Name', max_length=100, null=True)),
                ('photo7', models.ImageField(blank=True, null=True, upload_to='portfolio_images/')),
                ('description7', models.CharField(blank=True, default='Project Name', max_length=100, null=True)),
                ('photo8', models.ImageField(blank=True, null=True, upload_to='portfolio_images/')),
                ('description8', models.CharField(blank=True, default='Project Name', max_length=100, null=True)),
                ('photo9', models.ImageField(blank=True, null=True, upload_to='portfolio_images/')),
                ('description9', models.CharField(blank=True, default='Project Name', max_length=100, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
