# Generated by Django 5.0.6 on 2024-07-15 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='artist_name',
        ),
    ]
