# Generated by Django 5.0.6 on 2024-08-15 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_remove_artwork_artist_name_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='portfolio_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
