# Generated by Django 5.0.6 on 2024-08-15 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0003_portfolio_portfolio_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='portfolio_url',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='template_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
