# Generated by Django 5.0.6 on 2024-08-15 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0004_remove_portfolio_portfolio_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='background_color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
