# Generated by Django 5.0.6 on 2024-07-23 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0004_artwork_portfolio_portfolio_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='portfolio',
        ),
    ]
