# Generated by Django 5.0.6 on 2024-07-23 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0005_remove_artwork_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='artworks',
            field=models.ManyToManyField(blank=True, related_name='portfolios', to='MyApp.artwork'),
        ),
    ]
