# Generated by Django 4.2.14 on 2024-07-24 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0005_remove_portfolio_user_delete_contactinfo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='art_description',
            field=models.TextField(blank=True, null=True, verbose_name='작품 상세 설명'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='art_title',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='작품 제목'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='author_info',
            field=models.TextField(blank=True, null=True, verbose_name='작가 설명'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='author_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='작가명'),
        ),
    ]
