# Generated by Django 4.2.14 on 2024-07-24 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0006_artwork_art_description_artwork_art_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='artworks/', verbose_name='이미지 1'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='artworks/', verbose_name='이미지 2'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='artworks/', verbose_name='이미지 3'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='artworks/', verbose_name='이미지 4'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='artworks/', verbose_name='이미지 5'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='image6',
            field=models.ImageField(blank=True, null=True, upload_to='artworks/', verbose_name='이미지 6'),
        ),
    ]
