# Generated by Django 5.0.6 on 2024-07-23 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0006_portfolio_artworks'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='template_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='템플릿 ID'),
        ),
    ]
