# Generated by Django 4.2.14 on 2024-07-24 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0007_artwork_image1_artwork_image2_artwork_image3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='artwork_description',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='artwork_title',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='image5',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='image6',
        ),
    ]
