# Generated by Django 5.0.6 on 2024-07-23 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0007_portfolio_template_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='artworks',
        ),
        migrations.AddField(
            model_name='artwork',
            name='portfolio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artworks', to='MyApp.portfolio'),
        ),
    ]
