# Generated by Django 5.0.6 on 2024-07-23 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0008_remove_portfolio_artworks_artwork_portfolio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='portfolio',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='template_id',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='user',
        ),
    ]
