# Generated by Django 5.0.7 on 2024-07-24 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0008_remove_artwork_artwork_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='artwork',
            old_name='art_title',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='art_description',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='artwork_image',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='author_info',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='author_name',
        ),
        migrations.AddField(
            model_name='artwork',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='작품 설명'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='artworks/', verbose_name='작품 이미지'),
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='포트폴리오 제목')),
                ('description', models.TextField(blank=True, null=True, verbose_name='포트폴리오 설명')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='artwork',
            name='portfolio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='artworks', to='MyApp.portfolio'),
        ),
    ]
