# Generated by Django 5.0.6 on 2024-07-23 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0009_remove_artwork_portfolio_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='portfolio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='artworks', to='MyApp.portfolio'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='template_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artwork',
            name='artwork_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='artwork_image',
            field=models.ImageField(upload_to='artworks/'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='artwork_title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='art_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='art_title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='author_name',
            field=models.CharField(max_length=100),
        ),
    ]
