# Generated by Django 5.0.6 on 2024-07-23 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0010_artwork_portfolio_portfolio_template_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='portfolio',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='template_id',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='user',
        ),
        migrations.AlterField(
            model_name='artwork',
            name='artwork_description',
            field=models.TextField(verbose_name='작품 설명'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='artwork_image',
            field=models.ImageField(upload_to='artworks/', verbose_name='작품 이미지'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='artwork_title',
            field=models.CharField(max_length=150, verbose_name='작품명'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='art_description',
            field=models.TextField(verbose_name='작품 설명'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='art_title',
            field=models.CharField(max_length=255, verbose_name='작품 제목'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='author_name',
            field=models.CharField(max_length=255, verbose_name='작가명'),
        ),
    ]
