# Generated by Django 5.0.6 on 2024-07-23 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0012_artwork_portfolio_portfolio_template_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='portfolio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='artworks', to='MyApp.portfolio'),
        ),
    ]
