# Generated by Django 5.0.6 on 2024-07-23 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0013_alter_artwork_portfolio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='template_id',
        ),
    ]
