# Generated by Django 5.0.6 on 2024-07-23 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0014_remove_portfolio_template_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='template_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
