# Generated by Django 5.0.6 on 2024-07-23 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0015_portfolio_template_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='portfolio',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='template_id',
        ),
    ]
