# Generated by Django 5.0.6 on 2024-07-23 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0016_remove_artwork_portfolio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='portfolio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artworks', to='MyApp.portfolio', verbose_name='포트폴리오'),
        ),
    ]
