# Generated by Django 5.0.6 on 2024-07-23 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0017_artwork_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='template_id',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
