# Generated by Django 5.0.6 on 2024-07-23 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0018_portfolio_template_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='portfolio',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='template_id',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='author_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='portfolios/'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='portfolios/'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='portfolios/'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='portfolios/'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='portfolios/'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='image6',
            field=models.ImageField(blank=True, null=True, upload_to='portfolios/'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='art_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='art_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='author_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
