# Generated by Django 5.0.6 on 2024-07-23 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0019_remove_artwork_portfolio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='portfolio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artworks', to='MyApp.portfolio'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='template_choice',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='artwork_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='artwork_image',
            field=models.ImageField(upload_to='artworks/'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='artwork_title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='homepage',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='instagram',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
