# Generated by Django 5.0.3 on 2024-07-24 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0010_alter_artwork_portfolio'),
        ('MyApp', '0020_artwork_portfolio_portfolio_description_and_more'),
    ]

    operations = [
    ]
